### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by mohaplc** [ClintOxx/vuetify-admin-dashboard#23]
> vuetify-admin-dashboard@1.0.0 serve C:\vuetify-admin-dashboard-master
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                                                                       17:48:23
 error  in ./src/router/paths.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\rules\template-curly-spacing.js:52:42)
    at TemplateElement (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\rules\template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\linter.js:865:28)
    at Traverser._traverse (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser._traverse (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (C:\vuetify-admin-dashboard-master\node_modules\eslint\lib\util\traverser.js:147:30)

 @ ./src/router/index.js 15:0-28 21:10-15

**Comment by SadovovAlex** [comment]
Same proble =(

**Comment by amphen4** [comment]
cloning this repo today i had this issue then i fixed on this way:

add the following attributes:

"template-curly-spacing" : "off",  
indent: "off" 

on rules property in .eslintrc.js

**Comment by anselal** [comment]
@amphen4 if this works just create a PR, although @ClintOxx has not responded in months

**Comment by ClintOxx** [comment]
Haven’t had the chance to look into it yet

**Comment by anselal** [comment]
@ClintOxx good to see you, I thought you abandoned the project

**Comment by ClintOxx** [comment]
I’ve commented a few times recently

**Comment by anselal** [comment]
@ClintOxx did maybe #26 fix this issue ? Cause it solved some linting errors.
@mohaplc can you download the latest master and re-check ?

**Comment by ClintOxx** [comment]
i promise i will get to this soon lol, the coronavirus messed up several of my plans for this part of the year so I'm trying to get myself in order

**Comment by anselal** [comment]
Sure man, no rush here. I just asked if it was resolved some how already by another PR

**Comment by EDMONDGIHOZO** [comment]
> cloning this repo today i had this issue then i fixed on this way:
> 
> add the following attributes:
> 
> "template-curly-spacing" : "off",
> indent: "off"
> 
> on rules property in .eslintrc.js

thanks, @anselal ,this helped me.

**Comment by anselal** [comment]
@EDMONDGIHOZO, this was provided by @amphen4, he takes the credits !!
