### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by omkar1117** [ClintOxx/vuetify-admin-dashboard#31]
```
ERROR  Failed to compile with 1 errors3:43:32 PM

 error  in ./src/router/paths.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (D:\admx\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (D:\admx\node_modules\eslint\lib\rules\template-curly-spacing.js:52:42)
    at TemplateElement (D:\admx\node_modules\eslint\lib\rules\template-curly-spacing.js:117:17)
    at D:\admx\node_modules\eslint\lib\util\safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\admx\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\admx\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (D:\admx\node_modules\eslint\lib\linter.js:865:28)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)

 @ ./src/router/index.js 15:0-28 21:10-15
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.5:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by ashrafreda** [comment]
+1

**Comment by evelaguti** [comment]
I encounter a similar error when building for production 
 ERROR  Failed to compile with 1 errors                                                  12:05:18 PM

 error  in ./src/router/paths.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'range' of null
    at PoolWorker.fromErrorObj (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at SourceCode.getTokenBefore (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/edo/Documents/dev/hostalmanantial/vuetify-admin-dashboard/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)

 @ ./src/router/index.js 15:0-28 21:10-15
 @ ./src/main.js
 @ multi ./src/main.js

**Comment by evelaguti** [comment]
I did this and it work 😮  👍 
https://github.com/babel/babel-eslint/issues/681#issuecomment-420663038

**Comment by piscomobile** [comment]
+1
